config/routes.rb
Rails.application.routes.draw do
  if !Rails.env.production? && Rails.application.config.action_mailer.delivery_method == :letter_opener_web
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users
  resources :bins, only: %i[index new create edit update destroy]
  resources :bin_locations, only: %i[index destroy]
  resources :categories, only: %i[new create edit update destroy]

  resources :counties, only: %i[new create edit update index] do
    collection do
      get :assigned
      get :unassigned
    end
  end

  resources :donations, only: %i[index new create show edit update destroy] do
    collection do
      get :closed
      get :deleted
      get :migrate
      post :migrate, action: :save_migration
    end

    member do
      post :close
      patch :restore
      post :sync
      delete :destroy_closed
    end
  end

  resources :donors, only: %i[index new edit update create destroy] do
    collection do
      get :deleted
      get :export
      post :netsuite_import
    end

    member do
      patch :restore
    end
  end

  resources :help_links, only: %i[index create destroy] do
    member do
      post :toggle_visibility
      post :move_up
      post :move_down
    end
  end

  resources :items, path: "/inventory" do
    collection do
      get :deleted
      get :bulk_pricing
      post :update_bulk_pricing
    end

    member do
      patch :restore
      get :edit_stock
    end
  end

  resources :item_program_ratios, only: %i[index new create edit update destroy]

  resources :inventory_reconciliations, only: %i[index create show destroy] do
    resources :count_sheets, only: %i[index show update destroy] do
      collection do
        delete :unnecessary, action: :destroy_unnecessary
      end
    end

    collection do
      get :print_prep
      get :completed
    end

    member do
      get :deltas
      get :ignored_bins
      post :unignore_bin
      post :comment
      post :complete
    end
  end

  resources :net_suite_errors, only: %i[index show destroy]
  resources :notifications, only: %i[index show update]

  resources :orders, only: %i[index new create edit update] do
    collection do
      get :rejected, :closed, :canceled
    end

    member do
      post :sync
      post :resync_journal_line_items
      get :survey_answers
    end
  end

  resources :organizations do
    collection do
      get :by_program
      get :deleted
      post :netsuite_import
    end

    member do
      patch :restore
    end
  end

  resources :programs, only: %i[index new create show update]

  resources :purchases, only: %i[index new create edit show update] do
    collection do
      get :closed, :canceled
    end

    member do
      post :sync
      patch :cancel
    end
  end

  resources :purchase_details, only: %i[create destroy]
  resources :purchase_shipments, only: %i[create destroy]
  resources :purchase_shorts, only: %i[create destroy]

  resources :reports, only: [] do
    collection do
      get :donor_receipts
      get :graphs
      get :inventory_adjustments
      get :net_suite_export
      get :total_inventory_value
      get :value_by_county
      get :value_by_donor
      get :price_point_variance
    end
  end

  resources :revenue_streams, only: %i[index new create show update destroy] do
    collection do
      get :deleted
    end

    member do
      patch :restore
    end
  end

  resources :surveys, only: %i[index new create show update destroy] do
    member do
      get :demo
      post :demo, action: :submit_demo
    end
  end

  resources :survey_requests, only: %i[index new create show] do
    resources :answers, only: %i[show update], controller: "survey_request_answers", param: :org_request_id do
      member do
        get :view
        post :skip
      end
    end

    member do
      get :email
      get :export
      get :report
      post :email, action: :submit_email
    end
  end

  resources :tracking_details

  resources :user_invitations, path: "/users/invitations", only: %i[new create show update] do
    collection do
      get :open
      get :closed
    end
  end

  resources :users, only: %i[index edit update destroy] do
    collection do
      get :deleted
      get :export
    end

    member do
      post :reset_password
    end
  end

  resources :vendors, only: %i[index new edit update create destroy] do
    collection do
      get :deleted
      post :netsuite_import
    end

    member do
      patch :restore
    end
  end

  resource :backup, only: :show
  resource :exports, only: :show
  resource :integrations, only: :show

  resource :profiler, only: [] do
    post :toggle
  end

  get "/.well-known/acme-challenge/:id" => "letsencrypt#authenticate"

  root to: "orders#index"
end

app/models/bin.rb
require "set"

class Bin < ApplicationRecord
  belongs_to :bin_location
  has_many :bin_items
  has_many :items, -> { order(:description) }, through: :bin_items
  has_many :order_details, through: :items

  validates :label, uniqueness: { conditions: -> { not_deleted } }

  delegate :rack, to: :bin_location, allow_nil: true
  delegate :shelf, to: :bin_location, allow_nil: true

  def to_json
    {
      id: id,
      label: label,
      location: bin_location.display
    }
  end

  def build_items(params)
    new_item_ids = bin_item_ids(params)
    new_item_ids -= bin_items.map(&:item_id)

    Item.where(id: new_item_ids).find_each do |item|
      bin_items.build(item: item)
    end
  end

  def delete_items!(params)
    item_ids_to_remove = bin_item_ids(params)
    item_ids_to_remove = Set.new(bin_items.map(&:item_id) - item_ids_to_remove)

    bin_items.each do |bin_item|
      bin_item.destroy! if item_ids_to_remove.include?(bin_item.item_id)
    end
  end

  def label_prefix
    label[/\A(.*?)\d*\z/, 1]
  end

  def label_suffix
    label[/(\d+)\z/, 1]
  end

  def self.not_deleted
    where(deleted_at: nil)
  end

  def self.for_print_prep
    includes(:bin_location, :items).order(:label)
  end

  def self.to_json
    includes(:bin_location).order(:label).map(&:to_json).to_json
  end

  def self.update_bin!(params)
    transaction do
      bin = Bin.not_deleted.find(params[:id])
      bin.bin_location = BinLocation.create_or_find_bin_location(params)
      bin.label = Bin.generate_label(params)
      bin.delete_items!(params)
      bin.build_items(params)
      bin.save!
    end
  end

  def self.create_bin!(params)
    transaction do
      Bin.create! do |bin|
        bin.bin_location = BinLocation.create_or_find_bin_location(params)
        bin.label = Bin.generate_label(params)
        bin.build_items(params)
      end
    end
  end

  def self.generate_label(params)
    label_params = params.permit(:label_prefix, :label_suffix)
    prefix = label_params[:label_prefix]
    suffix = label_params[:label_suffix]
    raise "Prefix is required!" if prefix.blank?
    return "#{prefix}#{suffix}" if suffix.present?
    next_label_with_prefix(prefix)
  end

  def self.next_label_with_prefix(prefix)
    pattern = /\A#{Regexp.escape(prefix)}\d+\z/
    max_existing = 0

    Bin.not_deleted.where("label LIKE ?", "#{prefix}%").find_each do |bin|
      next unless bin.label.match?(pattern)
      value = bin.label[/\d+/].to_i
      max_existing = value if value > max_existing
    end

    "#{prefix}#{max_existing + 1}"
  end

  private

  def bin_item_ids(params)
    params.permit(bin_items: { item_id: [] }).fetch(:bin_items, {}).fetch(:item_id, []).map(&:to_i)
  end
end

app/controllers/bins_controller.rb
class BinsController < ApplicationController
  require_permission :can_view_bins?
  require_permission :can_edit_bins?, except: [:index]
  active_tab "inventory"

  def index
    @bins = Bin.not_deleted.includes(:bin_location, :items).all.to_a
  end

  def new; end

  def create
    current_user.create_bin(params)
    redirect_to bins_path, flash: { success: "Bin created!" }
  end

  def edit
    @bin = Bin.not_deleted.find(params[:id])
  end

  def update
    current_user.update_bin(params)
    redirect_to bins_path, flash: { success: "Bin updated!" }
  end

  def destroy
    current_user.destroy_bin(params)
    redirect_to bins_path, flash: { success: "Bin deleted!" }
  end
end

app/views/bins/_bin_item_row_template.html.erb
<script type="text/x-tmpl" id="bin-item-row-template">
  <tr class="bin-item-row">
    <td>
      <div class="form-group select-item">
        {%# tmpl("item-selector-template", { name: "bin_items[item_id][]", guard: "binitemdupes" }) %}
      </div>
    </td>

    <td>
      <button class="pull-right btn btn-danger btn-xs table-editable-delete">
        <span class="glyphicon glyphicon-trash"></span>
      </button>
    </td>
  </tr>
</script>

app/views/bins/_existing_bin_location_template.html.erb
<script type="text/x-tmpl" id="existing-bin-location-template">
  <div class="col-sm-6">
    <div class="form-group">
      <label>Rack:</label>
      <div>{%= o.rack %}</div>
    </div>
  </div>

  <div class="col-sm-6">
    <div class="form-group">
      <label>Shelf:</label>
      <div>{%= o.shelf %}</div>
    </div>
  </div>
</script>

app/views/bins/_new_bin_location_template.html.erb
<script type="text/x-tmpl" id="new-bin-location-template">
  <div class="col-sm-6">
    <div class="form-group">
      <label for="bin-location-rack">Rack:</label>
      <input type="text" id="bin-location-rack" name="rack" class="form-control" placeholder="Example: R0001" data-guard="required binLocationUnique" />
      <div id="bin-location-error-target"></div>
    </div>
  </div>

  <div class="col-sm-6">
    <div class="form-group">
      <label for="bin-location-shelf">Shelf:</label>
      <input type="text" id="bin-location-shelf" name="shelf" class="form-control" placeholder="Example: S0001" data-guard="binLocationUnique" />
    </div>
  </div>
</script>

app/views/bins/edit.html.erb
<% content_for :title, "Edit Bin #{@bin.label}" %>
<% content_for :tabs, render("items/tabs") %>

<% content_for :content do %>
  <%= render partial: "bins/bin_item_row_template" %>
  <%= render partial: "bins/existing_bin_location_template" %>
  <%= render partial: "bins/new_bin_location_template" %>
  <%= render partial: "items/item_selector_template" %>

  <input type="hidden" id="data-categories" data-value="<%= Category.to_json %>" />
  <input type="hidden" id="data-bin-selected-items" data-value="<%= @bin.items.map { |item| item.id.to_s }.to_json %>" />

  <%= form_tag bin_path(@bin), method: :put, data: { live_guarded: true } do %>
    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <label for="bin-label-prefix">Label Prefix</label>
          <input id="bin-label-prefix" type="text" class="form-control" placeholder="Example: A" name="label_prefix" value="<%= @bin.label_prefix %>" data-guard="required" />
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <label for="bin-label-suffix">Label Suffix</label>
          <input id="bin-label-suffix" type="text" class="form-control" placeholder="Leave blank to generate" name="label_suffix" value="<%= @bin.label_suffix %>" />
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <label for="bin-location-selector">Location</label>

          <select id="bin-location-selector" class="select2-with-customized-search-text" name="selected_bin_location" data-guard="required" data-guard-required-target="#bin-location-selector-error-target">
            <option value="">Select a location...</option>
            <option value="new">New location</option>

            <% BinLocation.all.each do |location| %>
              <option value="<%= location.id %>" data-rack="<%= location.rack %>" data-shelf="<%= location.shelf %>" data-search-text="Rack <%= location.rack %> - Shelf <%= location.shelf %>" <%= "selected" if location == @bin.bin_location %>><%= location.display %></option>
            <% end %>
          </select>

          <div id="bin-location-selector-error-target"></div>
        </div>
      </div>
    </div>

    <div class="row">
      <div id="existing-bin-location-fields" style="display: none;"></div>
      <div id="new-bin-location-fields" style="display: none;"></div>
    </div>

    <div class="row">
      <div class="col-xs-12">
        <table id="bin-items-table" class="table table-hover table-striped table-editable" data-table-editable-row-template-id="bin-item-row-template" data-table-editable-allow-no-rows>
          <thead>
            <tr>
              <th>Item</th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <%# Dynamically generated %>
          </tbody>
        </table>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12">
        <div class="form-group">
          <button type="button" class="btn btn-default table-editable-add" data-table-editable-for="bin-items-table">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add Item
          </button>
        </div>
      </div>
    </div>

    <div>
      <input type="submit" class="btn btn-primary" value="Save" />
      <%= link_to "Cancel", bins_path, class: "btn btn-link" %>

      <% if @bin.bin_items.empty? %>
        <%= link_to "Delete", @bin, method: :delete, class: "btn btn-danger pull-right", data: confirm(title: "Deleting Bin: #{@bin.label}") %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/bins/index.html.erb
<% content_for :title, "Bins" %>
<% content_for :tabs, render("items/tabs") %>

<% content_for :content do %>
  <% if current_user.can_edit_bins? %>
    <h4 class="button-height">
      <%= link_to "Create Bin", new_bin_path, class: "btn btn-primary bottom15 pull-right" %>
    </h4>
  <% end %>

  <table class="table table-hover table-striped data-table">
    <thead>
      <tr>
        <th class="col-xs-3 sort-asc">Label</th>
        <th class="col-xs-3">Location</th>
        <th class="col-xs-6">Items</th>
      </tr>
    </thead>

    <tbody>
      <% @bins.each do |bin| %>
        <tr data-href="<%= edit_bin_path(bin) %>">
          <td class="col-xs-3"><%= bin.label %></td>
          <td class="col-xs-3"><%= bin.bin_location.display %></td>

          <td class="col-xs-6">
            <% bin.items.each do |item| %>
              <div>
                <%= item.description %>

                <% if current_user.can_view_and_edit_items? %>
                  <%= link_to '', edit_item_path(item.id), class: 'btn btn-default btn-xs glyphicon glyphicon-pencil', title: 'Edit Item' %>
                  <%= link_to '', edit_stock_item_path(item.id), class: 'btn btn-default btn-xs glyphicon glyphicon-th-list', title: 'Edit Current Quantity' %>
                <% end %>
              </div>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/bins/new.html.erb
<% content_for :title, "New Bin" %>
<% content_for :tabs, render("items/tabs") %>

<% content_for :content do %>
  <%= render partial: "bins/bin_item_row_template" %>
  <%= render partial: "bins/existing_bin_location_template" %>
  <%= render partial: "bins/new_bin_location_template" %>
  <%= render partial: "items/item_selector_template" %>

  <input type="hidden" id="data-categories" data-value="<%= Category.to_json %>" />
  <input type="hidden" id="data-bin-selected-items" data-value="[]" />

  <%= form_tag bins_path, method: :post, data: { live_guarded: true } do %>
    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <label for="bin-label-prefix">Label Prefix</label>
          <input id="bin-label-prefix" type="text" class="form-control" placeholder="Example: A" name="label_prefix" data-guard="required" />
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <label for="bin-label-suffix">Label Suffix</label>
          <input id="bin-label-suffix" type="text" class="form-control" placeholder="Leave blank to generate" name="label_suffix" />
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <label for="bin-location-selector">Location</label>

          <select id="bin-location-selector" class="select2-with-customized-search-text" name="selected_bin_location" data-guard="required" data-guard-required-target="#bin-location-selector-error-target">
            <option value="">Select a location...</option>
            <option value="new">New location</option>

            <% BinLocation.all.each do |location| %>
              <option value="<%= location.id %>" data-rack="<%= location.rack %>" data-shelf="<%= location.shelf %>" data-search-text="Rack <%= location.rack %> - Shelf <%= location.shelf %>"><%= location.display %></option>
            <% end %>
          </select>

          <div id="bin-location-selector-error-target"></div>
        </div>
      </div>
    </div>

    <div class="row">
      <div id="existing-bin-location-fields" style="display: none;"></div>
      <div id="new-bin-location-fields" style="display: none;"></div>
    </div>

    <div class="row">
      <div class="col-xs-12">
        <table id="bin-items-table" class="table table-hover table-striped table-editable" data-table-editable-row-template-id="bin-item-row-template">
          <thead>
            <tr>
              <th>Item</th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <%# Dynamically generated %>
          </tbody>
        </table>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12">
        <div class="form-group">
          <button type="button" class="btn btn-default table-editable-add" data-table-editable-for="bin-items-table">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add Item
          </button>
        </div>
      </div>
    </div>

    <div>
      <input type="submit" class="btn btn-primary" value="Create" />
      <%= link_to "Cancel", bins_path, class: "btn btn-link" %>
    </div>
  <% end %>
<% end %>