config/routes.rb
Rails.application.routes.draw do
  if !Rails.env.production? && Rails.application.config.action_mailer.delivery_method == :letter_opener_web
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users
  resources :bins, only: %i[index new create edit update destroy]
  resources :bin_locations, only: %i[index destroy]
  resources :categories, only: %i[new create edit update destroy]

  resources :counties, only: %i[new create edit update index] do
    collection do
      get :assigned
      get :unassigned
    end
  end

  resources :donations, only: %i[index new create show edit update destroy] do
    collection do
      get :closed
      get :deleted
      get :migrate
      post :migrate, action: :save_migration
    end

    member do
      post :close
      patch :restore
      post :sync
      delete :destroy_closed
    end
  end

  resources :donors, only: %i[index new edit update create destroy] do
    collection do
      get :deleted
      get :export
      post :netsuite_import
    end

    member do
      patch :restore
    end
  end

  resources :help_links, only: %i[index create destroy] do
    member do
      post :toggle_visibility
      post :move_up
      post :move_down
    end
  end

  resources :items, path: "/inventory" do
    collection do
      get :deleted
      get :bulk_pricing
      post :update_bulk_pricing
    end

    member do
      patch :restore
      get :edit_stock
    end
  end

  resources :item_program_ratios, only: %i[index new create edit update destroy]

  resources :inventory_reconciliations, only: %i[index create show destroy] do
    resources :count_sheets, only: %i[index show update destroy] do
      collection do
        delete :unnecessary, action: :destroy_unnecessary
      end
    end

    collection do
      get :print_prep
      get :completed
    end

    member do
      get :deltas
      get :ignored_bins
      post :unignore_bin
      post :comment
      post :complete
    end
  end

  resources :net_suite_errors, only: %i[index show destroy]
  resources :notifications, only: %i[index show update]

  resources :orders, only: %i[index new create edit update] do
    collection do
      get :rejected, :closed, :canceled
    end

    member do
      post :sync
      post :resync_journal_line_items
      get :survey_answers
    end
  end

  resources :organizations do
    collection do
      get :by_program
      get :deleted
      post :netsuite_import
    end

    member do
      patch :restore
    end
  end

  resources :programs, only: %i[index new create show update]

  resources :purchases, only: %i[index new create edit show update] do
    collection do
      get :closed, :canceled
    end

    member do
      post :sync
      patch :cancel
    end
  end

  resources :purchase_details, only: %i[create destroy]
  resources :purchase_shipments, only: %i[create destroy]
  resources :purchase_shorts, only: %i[create destroy]

  resources :reports, only: [] do
    collection do
      get :donor_receipts
      get :graphs
      get :inventory_adjustments
      get :net_suite_export
      get :total_inventory_value
      get :value_by_county
      get :value_by_donor
      get :price_point_variance
    end
  end

  resources :revenue_streams, only: %i[index new create show update destroy] do
    collection do
      get :deleted
    end

    member do
      patch :restore
    end
  end

  resources :surveys, only: %i[index new create show update destroy] do
    member do
      get :demo
      post :demo, action: :submit_demo
    end
  end

  resources :survey_requests, only: %i[index new create show] do
    resources :answers, only: %i[show update], controller: "survey_request_answers", param: :org_request_id do
      member do
        get :view
        post :skip
      end
    end

    member do
      get :email
      get :export
      get :report
      post :email, action: :submit_email
    end
  end

  resources :tracking_details

  resources :user_invitations, path: "/users/invitations", only: %i[new create show update] do
    collection do
      get :open
      get :closed
    end
  end

  resources :users, only: %i[index edit update destroy] do
    collection do
      get :deleted
      get :export
    end

    member do
      post :reset_password
    end
  end

  resources :vendors, only: %i[index new edit update create destroy] do
    collection do
      get :deleted
      post :netsuite_import
    end

    member do
      patch :restore
    end
  end

  resource :backup, only: :show
  resource :exports, only: :show
  resource :integrations, only: :show

  resource :profiler, only: [] do
    post :toggle
  end

  get "/.well-known/acme-challenge/:id" => "letsencrypt#authenticate"

  root to: "orders#index"
end

app/models/donor.rb
class Donor < ApplicationRecord
  include SoftDeletable

  validates :name, uniqueness: true
  validates :email, uniqueness: true, allow_nil: true
  before_validation { self.email = nil if email.blank? }

  belongs_to :county, optional: true

  has_many :donations
  has_many :donor_addresses, dependent: :destroy
  has_many :addresses, through: :donor_addresses

  accepts_nested_attributes_for :addresses, allow_destroy: true

  alias_attribute :cell_number, :primary_number

  def self.find_any(id)
    unscoped.find(id)
  end

  def sync_status_available?
    external_id.present?
  end

  def synced?
    external_id.present? && !NetSuiteIntegration.export_failed?(self)
  end

  def first_address
    addresses.first
  end

  def primary_address
    first_address&.address
  end

  def self.permitted_donor_params(params)
    donor_params = params.require(:donor)

    donor_params[:addresses_attributes].select! do |_, h|
      h[:address].present? || %i[street_address city state zip].all? { |k| h[k].present? }
    end

    donor_params.permit(:name, :external_id, :email, :external_type,
                        :primary_number, :secondary_number, :county_id,
                        addresses_attributes: %i[address street_address city state zip id])
  end
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  require_permission :can_view_donors?,               only: %i[index edit]
  require_permission :can_create_donors?,             only: %i[new create netsuite_import]
  require_permission :can_update_donors?,             only: :update
  require_permission :can_delete_and_restore_donors?, only: %i[destroy deleted restore]
  require_permission one_of: %i[can_create_donors? can_update_donors?], except: %i[new create netsuite_import]
  require_permission :can_view_reports?, only: [:export]

  active_tab "donors"

  def index
    @donors = Donor.includes(:addresses, :county).active
  end

  def export
    send_csv Reports::DonorExport.new(current_user, session),
             filename: "donors-#{Time.zone.now.strftime('%Y%m%d%H%M%S')}.csv"
  end

  def new
    @donor = Donor.new
  end

  def edit
    @redirect_to = Redirect.to(donors_path, params, allow: %i[order users user])
    @donor = Donor.find params[:id]
  end

  def update
    current_user.update_donor params
    redirect_to donors_path
  end

  def netsuite_import
    donor = current_user.create_donor(params, via: :netsuite_import)
    redirect_to edit_donor_path(donor)
  rescue ActiveRecord::RecordInvalid => e
    @show_tab = "netsuite-import"
    @donor = e.record
    flash.now[:error] = e.message
    render :new
  end

  def create
    current_user.create_donor params
    redirect_to donors_path
  rescue ActiveRecord::RecordInvalid => e
    @donor = e.record
    flash.now[:error] = e.message
    render :new
  end

  def destroy
    @donor = Donor.find params[:id]

    begin
      @donor.soft_delete
      flash[:success] = "Donor '#{@donor.name}' deleted!"
    rescue DeletionError => e
      flash[:error] = e.message
    rescue
      flash[:error] = <<-eos
        We were unable to delete the donor as requested.
        Please try again or contact a system administrator.
      eos
    end

    redirect_to donors_path
  end

  def deleted
    @donors = Donor.deleted
  end

  def restore
    @donor = Donor.find params[:id]
    @donor.restore

    redirect_to donors_path(@donor)
  end
end

app/helpers/donors_helper.rb
module DonorsHelper
  def cancel_edit_donor_path
    Redirect.to(donors_path, params, allow: %i[order users])
  end
end

app/views/donors/_donor_fields.html.erb
<% if local_assigns[:auto_export] %>
  <input type="hidden" name="save_and_export_donor" value="true" />
<% end %>

<fieldset id="donor_info">
  <div class="col-xs-12 col-sm-<%= local_assigns[:auto_export] ? 12 : 9 %>">
    <div class="form-group">
      <%= fields.label :name %>
      <%= fields.text_field :name, class: "form-control", data: { guard: "required" } %>
    </div>
  </div>

  <% unless local_assigns[:auto_export] %>
    <div class="col-xs-12 col-sm-3">
      <%= render partial: "common/external_id_field", locals: { fields: fields, record: donor } %>
    </div>
  <% end %>

  <div class="col-xs-12 col-sm-3">
    <div class="form-group">
      <%= fields.label :email %>
      <%= fields.text_field :email, class: "form-control", data: { guard: "email" } %>
    </div>
  </div>

  <div class="col-xs-12 col-sm-3">
    <div class="form-group">
      <%= fields.label :primary_number, "Cell Phone" %>
      <%= fields.telephone_field :primary_number, class: "form-control", placeholder: "(408) 555-1234", data: { guard: "phoneUS" } %>
    </div>
  </div>

  <div class="col-xs-12 col-sm-3">
    <div class="form-group">
      <%= fields.label :secondary_number, "Other Phone" %>
      <%= fields.telephone_field :secondary_number, class: "form-control", placeholder: "(408) 555-1234", data: { guard: "phoneUS" } %>
    </div>
  </div>

  <div class="col-xs-12 col-sm-3">
    <div class="form-group">
      <%= fields.label :external_type %>
      <%= fields.select :external_type, options_for_select(external_types_for_select, donor.external_type), { include_blank: true }, { id: "external-type", data: { guard: "required", guard_required_target: "#external-type-error-target" } } %>

      <div id="external-type-error-target"></div>
    </div>
  </div>

  <%= fields.fields_for :addresses, (donor.addresses.build if donor.addresses.empty?) do |address| %>
    <% if address.object.all_parts_present? || address.object.new_record? %>
      <div class="col-xs-12">
        <h4>Mailing Address</h4>
        <div class="row">
          <div class="col-sm-4">
            <div class="form-group">
              <%= address.label :street_address, "Street Address" %>
              <%= address.text_field :street_address, class: "form-control", placeholder: "Example: 123 Street Address", data: { guard: "allOrNone", guard_all_or_none_target: "#address-error" } %>
              <span class="help-block" id="address-error"></span>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="form-group">
              <%= address.label :city, "City" %>
              <%= address.text_field :city, class: "form-control", placeholder: "Example: Some City", data: { guard: "allOrNone", guard_all_or_none_target: "#address-error" } %>
            </div>
          </div>
          <div class="col-sm-2">
            <div class="form-group">
              <%= address.label :state, "State" %>
              <%= address.text_field :state, class: "form-control", placeholder: "Example: CA", data: { guard: "allOrNone", guard_all_or_none_target: "#address-error" } %>
            </div>
          </div>
          <div class="col-sm-2">
            <div class="form-group">
              <%= address.label :zip, "Zip" %>
              <%= address.text_field :zip, class: "form-control", placeholder: "Example: 95123", data: { guard: "allOrNone", guard_all_or_none_target: "#address-error" } %>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <div class="col-xs-9">
        <div class="form-group">
          <%= address.label :address, "Mailing Address" %>
          <%= address.text_field :address, class: "form-control", data: { guard: "different" } %>
        </div>
      </div>
    <% end %>
  <% end %>

  <div class="col-xs-12 col-sm-3">
    <div class="form-group">
      <%= fields.label :county_id, "County" %>
      <%= fields.select :county_id, options_for_select(County.for_donors.select_options, donor.county&.id), { include_blank: true }, { class: "form-control select2", data: { guard: "required", guard_required_target: "#county-error-target" } } %>

      <div id="county-error-target"></div>
    </div>
  </div>
</fieldset>

app/views/donors/_receipt.html.erb
<div style="padding: 50px 80px;">
  <p>
    <img width="100%" class="img-responsive" src="<%= path_to_image("header-logo.png") %>" />
  </p>

  <p>
    <%= receipt.date.strftime("%B %-d, %Y") %>
  </p>

  <p>
    <%= receipt.donor_full_name %>

    <% if receipt.donor_address.present? %>
      <br /><%= receipt.donor_address_line_1 %>

      <% if receipt.donor_address_line_2.present? %>
        <br /><%= receipt.donor_address_line_2 %>
      <% end %>
    <% end %>

    <% if receipt.donor_email.present? %>
      <br/><%= receipt.donor_email %>
    <% end %>
  </p>

  <p>
    RE: Your Thank You and Tax Receipt
  </p>

  <p>
    Dear <%= receipt.donor_first_name %>,
  </p>

  <p>
    Thank you for your commitment to The Grateful Garment Project's mission to
    ensure that all sexual assault victims who cross the threshold of SART
    facilities or who go through the examination process are provided with
    whatever new clothing, toiletry and snack items they may require to reduce any
    additional impact on their being.
  </p>

  <p>
    We are delighted to have you as part of our caring family. The donation you
    made of <%= pluralize receipt.total_items, "brand new item" %> will help us
    provide the most humane care possible.  The Grateful Garment Project is a
    501(c)(3) not-for-profit organization.  Our Tax ID Number is
    <%= Rails.application.config.tax_id %>. In accordance with Internal Revenue
    Code 6115, we hereby state your donation is tax deductible.
  </p>

  <p>
    The entire The Grateful Garment Project family, of which you are a vital part,
    joins me in thanking you for your support.  Please feel free to call us at
    <%= Rails.application.config.contact_phone_formatted %> to share your comments
    or suggestions.
  </p>

  <p>
    Gratefully yours,<br />
    Lisa J. Blanchard<br />
    Executive Director
  </p>

  <p>
    <%= Rails.application.config.contact_street_address_line %>, <%= Rails.application.config.contact_city_line %><br />
    <%= Rails.application.config.contact_phone_formatted %> - <%= Rails.application.config.contact_email %>
  </p>

  <div class="page-break"></div>

  <table class="table">
    <thead>
      <tr>
        <th>Item</th>
        <th>Quantity</th>
      </tr>
    </thead>

    <tbody>
      <% receipt.donation_items.each do |item| %>
        <tr>
          <td><%= item.description %></td>
          <td><%= item.quantity %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/donors/_tabs.html.erb
<div class="row">
  <div class="col-xs-6">
    <ul class="nav nav-pills">
      <%= tab("Donors", donors_path, params[:controller] == "donors" && params[:action] != "deleted") %>

      <% if current_user.can_delete_and_restore_donors? %>
        <%= tab("Deleted Donors", deleted_donors_path, params[:controller] == "donors" && params[:action] == "deleted") %>
      <% end %>
    </ul>
  </div>

  <% if current_user.can_create_donors? || current_user.can_view_reports? %>
    <div class="col-xs-6">
      <div class="pull-right">
        <% if current_user.can_view_reports? && local_assigns[:export] %>
          <%= link_to "Export", export_donors_path, class: "btn btn-primary", data: { turbolinks: false } %>
        <% end %>

        <% if current_user.can_create_donors? %>
          <%= link_to "New Donor", new_donor_path, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<br />

app/views/donors/deleted.html.erb
<% content_for :title, "Deleted Donors" %>

<% content_for :content do %>
  <%= render partial: "donors/tabs" %>

  <div class="table-responsive">
    <table class="table table-striped data-table sort-asc">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @donors.each do |donor| %>
          <tr data-href="<%= edit_donor_path(donor) %>">
            <td><%= donor.name %></td>
            <td><%= donor.email %></td>
            <td class="col-xs-1">
              <%= link_to "", restore_donor_path(donor), method: :patch, class: 'btn btn-success btn-xs glyphicon glyphicon-plus' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/donors/edit.html.erb
<% content_for :title, "Edit #{@donor.name}" %>

<% content_for :content_size, "col-sm-9 col-md-10" %>

<% content_for :content do %>
  <%= form_for @donor, data: { guarded: true } do |f| %>
    <div class="row">
      <%= render partial: "donors/donor_fields", locals: { donor: @donor, fields: f } %>
    </div>

    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to "Cancel", cancel_edit_donor_path, type: "button", class: "btn btn-default" %>
    <%= link_to "Delete", donor_path(@donor), method: :delete, class: "btn btn-danger pull-right", data: confirm(title: "Deleting Donor: #{@donor.name}") %>
  <% end %>
<% end %>

app/views/donors/index.html.erb
<% content_for :title, "Donors" %>

<% content_for :content do %>
  <%= render partial: "donors/tabs", locals: { export: true } %>

  <div class="row">
    <div class="col-xs-12">
      <table class="table table-striped table-responsive data-table">
        <thead>
          <tr>
            <th>County</th>
            <th>Name</th>
            <th>Email</th>
            <th>Cell Phone</th>
            <th>Other Phone</th>
            <th>Address</th>
            <th>Date Created</th>
            <th>External Id</th>
            <th>External Type</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @donors.each do |donor| %>
            <tr class="donor" data-donor-id="<%= donor.id %>" data-href="<%= edit_donor_path(donor) %>">
              <td><%= donor.county&.name %></td>
              <td title="<%= donor.name %>">
                <%= truncate donor.name, length: 25 %>
              </td>
              <td title="<%= donor.email %>">
                <%= truncate donor.email, length: 25 %>
              </td>
              <td title="<%= donor.primary_number %>">
                <%= truncate donor.primary_number, length: 13 %>
              </td>
              <td title="<%= donor.secondary_number %>">
                <%= truncate donor.secondary_number, length: 13 %>
              </td>
              <td title="<%= donor.primary_address %>">
                <%= truncate donor.primary_address, length: 20 %>
              </td>
              <td><%= donor.created_at.strftime("%-m/%-d/%Y") %></td>
              <td><%= external_id_or_status(donor, link: true) %></td>
              <td><%= donor.external_type %></td>
              <td class="col-xs-1">
                <%= link_to "", donor_path(donor), method: :delete,
                    class: 'btn btn-danger btn-xs glyphicon glyphicon-trash pull-right',
                    data: confirm(title: "Deleting Donor: #{donor.name}") if donor.persisted? %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/donors/new.html.erb
<% content_for :title, "New Donor" %>

<% content_for :content_size, "col-sm-9 col-md-10" %>

<% content_for :content do %>
  <div>
    <ul class="nav nav-pills" role="tablist">
      <li id="manual-creation-tab" role="presentation" class="<%= "active" unless showing_tab?("netsuite-import") %>"><a href="#manual-creation" aria-controls="manual-creation" role="tab" data-toggle="pill">Create</a></li>
      <li id="netsuite-import-tab" role="presentation" class="<%= "active" if showing_tab?("netsuite-import") %>"><a href="#netsuite-import" aria-controls="netsuite-import" role="tab" data-toggle="pill">Import From NetSuite</a></li>
    </ul>

    <br />

    <div class="tab-content">
      <div role="tabpanel" class="tab-pane <%= "active" unless showing_tab?("netsuite-import") %>" id="manual-creation">
        <%= form_for @donor, data: { guarded: true } do |f| %>
          <div class="row">
            <%= render partial: "donors/donor_fields", locals: { donor: @donor, fields: f } %>
          </div>

          <div class="row">
            <div class="col-xs-12 col-sm-9">
              <%= f.submit "Save", id: "save", class: "btn btn-primary save-donor-without-export" %>
              <%= f.button "Save and Export to NetSuite", id: "save_and_export", class: "btn btn-primary disable-on-external-id-change", type: "submit", name: "save_and_export_donor", value: "true", data: { disable_with: "Save and Export to NetSuite" } %>
              <%= link_to "Cancel", donors_path, class: "btn btn-default" %>
            </div>
          </div>
        <% end %>
      </div>

      <div role="tabpanel" class="tab-pane <%= "active" if showing_tab?("netsuite-import") %>" id="netsuite-import">
        <%= form_tag netsuite_import_donors_path, data: { live_guarded: true } do %>
          <div class="row">
            <div class="col-xs-12 col-sm-3">
              <div class="form-group">
                <label for="import_from_external_id">External Id</label>
                <input type="number" class="form-control" id="import_from_external_id" name="external_id" data-guard="required" value="<%= @donor.external_id %>" />
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-xs-12">
              <input type="submit" class="btn btn-primary" value="Save" />
              <%= link_to "Cancel", donors_path, class: "btn btn-default" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>