config/routes.rb
Rails.application.routes.draw do
  if !Rails.env.production? && Rails.application.config.action_mailer.delivery_method == :letter_opener_web
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users
  resources :bins, only: %i[index new create edit update destroy]
  resources :bin_locations, only: %i[index destroy]
  resources :categories, only: %i[new create edit update destroy]

  resources :counties, only: %i[new create edit update index] do
    collection do
      get :assigned
      get :unassigned
    end
  end

  resources :donations, only: %i[index new create show edit update destroy] do
    collection do
      get :closed
      get :deleted
      get :migrate
      post :migrate, action: :save_migration
    end

    member do
      post :close
      patch :restore
      post :sync
      delete :destroy_closed
    end
  end

  resources :donors, only: %i[index new edit update create destroy] do
    collection do
      get :deleted
      get :export
      post :netsuite_import
    end

    member do
      patch :restore
    end
  end

  resources :help_links, only: %i[index create destroy] do
    member do
      post :toggle_visibility
      post :move_up
      post :move_down
    end
  end

  resources :items, path: "/inventory" do
    collection do
      get :deleted
      get :bulk_pricing
      post :update_bulk_pricing
    end

    member do
      patch :restore
      get :edit_stock
    end
  end

  resources :item_program_ratios, only: %i[index new create edit update destroy]

  resources :inventory_reconciliations, only: %i[index create show destroy] do
    resources :count_sheets, only: %i[index show update destroy] do
      collection do
        delete :unnecessary, action: :destroy_unnecessary
      end
    end

    collection do
      get :print_prep
      get :completed
    end

    member do
      get :deltas
      get :ignored_bins
      post :unignore_bin
      post :comment
      post :complete
    end
  end

  resources :net_suite_errors, only: %i[index show destroy]
  resources :notifications, only: %i[index show update]

  resources :orders, only: %i[index new create edit update] do
    collection do
      get :rejected, :closed, :canceled
    end

    member do
      post :sync
      post :resync_journal_line_items
      get :survey_answers
    end
  end

  resources :organizations do
    collection do
      get :by_program
      get :deleted
      post :netsuite_import
    end

    member do
      patch :restore
    end
  end

  resources :programs, only: %i[index new create show update]

  resources :purchases, only: %i[index new create edit show update] do
    collection do
      get :closed, :canceled
    end

    member do
      post :sync
      patch :cancel
    end
  end

  resources :purchase_details, only: %i[create destroy]
  resources :purchase_shipments, only: %i[create destroy]
  resources :purchase_shorts, only: %i[create destroy]

  resources :reports, only: [] do
    collection do
      get :donor_receipts
      get :graphs
      get :inventory_adjustments
      get :net_suite_export
      get :total_inventory_value
      get :value_by_county
      get :value_by_donor
      get :price_point_variance
    end
  end

  resources :revenue_streams, only: %i[index new create show update destroy] do
    collection do
      get :deleted
    end

    member do
      patch :restore
    end
  end

  resources :surveys, only: %i[index new create show update destroy] do
    member do
      get :demo
      post :demo, action: :submit_demo
    end
  end

  resources :survey_requests, only: %i[index new create show] do
    resources :answers, only: %i[show update], controller: "survey_request_answers", param: :org_request_id do
      member do
        get :view
        post :skip
      end
    end

    member do
      get :email
      get :export
      get :report
      post :email, action: :submit_email
    end
  end

  resources :tracking_details

  resources :user_invitations, path: "/users/invitations", only: %i[new create show update] do
    collection do
      get :open
      get :closed
    end
  end

  resources :users, only: %i[index edit update destroy] do
    collection do
      get :deleted
      get :export
    end

    member do
      post :reset_password
    end
  end

  resources :vendors, only: %i[index new edit update create destroy] do
    collection do
      get :deleted
      post :netsuite_import
    end

    member do
      patch :restore
    end
  end

  resource :backup, only: :show
  resource :exports, only: :show
  resource :integrations, only: :show

  resource :profiler, only: [] do
    post :toggle
  end

  get "/.well-known/acme-challenge/:id" => "letsencrypt#authenticate"

  root to: "orders#index"
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :survey_revisions
  has_many :survey_requests
  has_many :program_surveys

  def self.available_for_programs
    order(:title).to_a.select { |survey| survey.active_revision.present? }
  end

  def self.available_for_requests
    order(:title).to_a.select { |survey| survey.active_revision.present? }
  end

  def to_option
    [title, id]
  end

  def deletable?
    survey_revisions.count == 1 && survey_requests.count == 0 && program_surveys.count == 0
  end

  def active_or_first_revision
    active_revision || first_revision
  end

  def active_revision
    survey_revisions.where(active: true).order(:created_at).first
  end

  def first_revision
    survey_revisions.order(:created_at).first
  end

  def activate_revision!(params)
    revision = survey_revisions.find(params[:revision_id])
    survey_revisions.update_all(active: false)
    revision.title = params[:revision_title]
    revision.active = true
    revision.save!
  end

  def update_revision!(params)
    revision = survey_revisions.find(params[:revision_id])
    revision.title = params[:revision_title]
    revision.save!
  end

  def save_new_revision!(params)
    definition = SurveyDef::Definition.from_params(params)

    survey_revisions.create! do |revision|
      revision.title = params[:revision_title]
      revision.active = params[:active] == "true"
      revision.definition = definition.serialize
    end
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :authenticate_user!
  require_permission :can_view_and_edit_surveys?
  require_permission :can_create_surveys?, only: %i[new create update]
  require_permission :can_delete_surveys?, only: %i[destroy]
  active_tab "surveys"

  def index
    @surveys = Survey.order(:title)
  end

  def new
    @survey = Survey.new(title: "New Survey")
    @revision = SurveyRevision.new(survey: @survey, title: "Initial Revision")
  end

  def create
    definition = SurveyDef::Definition.from_params(params)

    survey = Survey.create! do |s|
      s.title = params[:survey_title]
    end

    survey.survey_revisions.create! do |revision|
      revision.title = params[:revision_title]
      revision.active = params[:active] == "true"
      revision.definition = definition.serialize
    end

    redirect_to surveys_path, flash: { success: "Survey created!" }
  end

  def show
    @survey = Survey.find(params[:id])

    @revision =
      if params[:revision_id].present?
        @survey.survey_revisions.find(params[:revision_id])
      else
        @survey.active_or_first_revision
      end
  end

  def update # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
    flash = {}
    revision_id = params[:revision_id]

    begin
      Survey.transaction do
        survey = Survey.find(params[:id])
        survey.title = params[:survey_title]
        survey.save!

        if params[:activate].present?
          survey.activate_revision!(params)
          flash[:success] = "Revision successfully activated!"
        elsif params[:update].present?
          survey.update_revision!(params)
          flash[:success] = "Revision successfully updated!"
        elsif params[:save_new_revision].present?
          revision_id = survey.save_new_revision!(params).id
          flash[:success] = "New revision successfully created!"
        else
          flash[:error] = "Unknown action!"
          raise ActiveRecord::Rollback
        end
      end
    rescue ActiveRecord::RecordNotUnique
      flash[:error] = "Duplicate name detected, action failed!"
    end

    redirect_to survey_path(params[:id], revision_id: revision_id), flash: flash
  end

  def destroy
    Survey.transaction do
      survey = Survey.find(params[:id])
      revision = survey.survey_revisions.find(params[:revision_id])
      raise "Revision is not deletable!" unless revision.deletable?

      message = "Revision successfully deleted!"
      revision.destroy!

      if survey.survey_revisions.count == 0
        message = "Survey successfully deleted!"
        survey.destroy!
      end

      redirect_to surveys_path, flash: { success: message }
    end
  end

  def demo
    @survey = Survey.find(params[:id])
    @revision =
      if params[:revision_id].present?
        @survey.survey_revisions.find(params[:revision_id])
      else
        @survey.active_or_first_revision
      end
  end

  def submit_demo
    @survey = Survey.find(params[:id])
    survey_params = params[:survey_answers][params[:id]]
    @revision = @survey.survey_revisions.find(survey_params[:revision])
    @answers = @revision.to_definition.answers_from_params(survey_params[:answers])
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
  def survey_answer_value(answer)
    if answer.value.present?
      answer.display_value
    else
      tag.em "No answer provided", class: "text-danger"
    end
  end
end

app/views/surveys/_survey_answer_fields.html.erb
<input type="hidden" name="survey_answers[<%= survey.id %>][revision]" value="<%= revision.id %>" />

<div id="survey-answer-fields-<%= survey.id %>">
</div>

<% unless @_rendered_survey_answer_field_templates %>
  <% @_rendered_survey_answer_field_templates = true %>

  <% SurveyDef::Definition::FIELDS.each do |field| %>
    <%= render partial: "surveys/field_templates/answering/#{field.type}" %>
  <% end %>
<% end %>

<input type="hidden" id="data-survey-answers-field-container-id" data-value="survey-answer-fields-<%= survey.id %>" />
<input type="hidden" id="data-survey-answers-scope" data-value="survey_answers[<%= survey.id %>]" />
<input type="hidden" id="data-survey-answers-survey-data" data-value="<%= revision.to_definition.to_answers_json %>" />
<input type="hidden" id="data-survey-answers-answer-data" data-value="<%= answers.to_json %>" />

app/views/surveys/_survey_answers.html.erb
<% answers.values.each do |answer| %>
  <%= render partial: "surveys/field_templates/answers/#{answer.template_name}", locals: { survey: survey, revision: revision, answer: answer } %>
<% end %>

app/views/surveys/_survey_fields.html.erb
<%= render partial: "surveys/field_templates/field" %>

<% SurveyDef::Definition::FIELDS.each do |field| %>
  <%= render partial: "surveys/field_templates/editing/#{field.type}" %>
<% end %>

<input type="hidden" id="data-survey-global-data" data-value="<%= SurveyDef::Definition.to_h.to_json %>" />
<input type="hidden" id="data-survey-data" data-value="<%= revision.definition.to_json %>" />

<div class="row">
  <div class="col-xs-6">
    <div class="form-group">
      <label class="control-label" for="survey-title">Survey Title</label>
      <input type="text" class="form-control" id="survey-title" name="survey_title" placeholder="Title for the survey" value="<%= survey.title %>" data-guard="required" autocomplete="off" />
    </div>
  </div>

  <div class="col-xs-2 col-xs-offset-3">
    <% unless survey.new_record? %>
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Change Revision <span class="caret"></span>
        </button>

        <ul class="dropdown-menu">
          <% survey.survey_revisions.each do |rev| %>
            <li>
              <%= link_to survey_path(survey, revision_id: rev.id) do %>
                <%= rev.title %>

                <% if rev.active? %>
                  <em>(active)</em>
                <% end %>

                <% if rev.id == revision.id %>
                  <em>(current)</em>
                <% end %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>

  <div class="col-xs-1">
    <% if revision.active? %>
      <span class="label label-success">Active</span>
    <% else %>
      <span class="label label-default">Inactive</span>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-xs-6">
    <div class="form-group">
      <label class="control-label" for="revision-title">Revision Title</label>
      <input type="text" class="form-control" id="revision-title" name="revision_title" placeholder="Title for the survey" value="<%= revision.title %>" data-guard="required" autocomplete="off" />
    </div>
  </div>
</div>

<div id="survey-fields">
</div>

<p>
  <button id="add-survey-field" type="button" class="btn btn-primary">Add Field</button>
</p>

app/views/surveys/_tabs.html.erb
<div class="row">
  <div class="col-xs-6">
    <ul class="nav nav-pills">
      <%= tab("Surveys", surveys_path, params[:controller] == "surveys" && params[:action] == "index") %>
      <%= tab("Requests", survey_requests_path, params[:controller] == "survey_requests" && params[:action] == "index") %>
      <%= tab("Orders", order_surveys_path, params[:controller] == "order_surveys" && params[:action] == "index") %>
    </ul>
  </div>
</div>

<br />

app/views/surveys/demo.html.erb
<% content_for :title, "Demo Survey" %>

<% content_for :content_size, "col-sm-9 col-md-10" %>

<% content_for :content do %>
  <h3><%= @survey.title %> <small><em><%= @revision.title %></em></small></h3>

  <%= form_tag demo_survey_path(@survey), method: :post, data: { live_guarded: true } do %>
    <%= render partial: "surveys/survey_answer_fields", locals: { survey: @survey, revision: @revision, answers: @revision.blank_answers } %>
    <input type="submit" name="Submit" class="btn btn-primary" />
    <%= link_to "Cancel", survey_path(@survey, revision_id: @revision.id), class: "btn btn-default" %>
  <% end %>
<% end %>

app/views/surveys/index.html.erb
<% content_for :title, "Surveys" %>

<% content_for :content do %>
  <%= render partial: "surveys/tabs" %>

  <div class="row">
    <div class="col-xs-12">
      <div class="pull-right">
        <%= link_to "New Survey", new_survey_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>

  <br />

  <div class="row">
    <div class="col-xs-12">
      <table class="table table-striped table-responsive data-table">
        <thead>
          <tr>
            <th>Title</th>
          </tr>
        </thead>

        <tbody>
          <% @surveys.each do |survey| %>
            <tr data-href="<%= survey_path(survey) %>">
              <td>
                <%= survey.title %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/surveys/new.html.erb
<% content_for :title, "Create Survey" %>

<% content_for :content_size, "col-sm-9 col-md-10" %>

<% content_for :content do %>
  <%= form_for @survey, data: { live_guarded: true } do |f| %>
    <%= render partial: "surveys/survey_fields", locals: { fields: f, survey: @survey, revision: @revision } %>
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to "Cancel", surveys_path, type: "button", class: "btn btn-default" %>
  <% end %>
<% end %>

app/views/surveys/show.html.erb
<% content_for :title, "Edit Survey" %>

<% content_for :content_size, "col-sm-9 col-md-10" %>

<% content_for :content do %>
  <%= form_for @survey, data: { live_guarded: true } do |f| %>
    <input type="hidden" id="original-revision-title" value="<%= @revision.title %>" />
    <input type="hidden" name="revision_id" value="<%= @revision.id %>" />
    <%= render partial: "surveys/survey_fields", locals: { fields: f, survey: @survey, revision: @revision } %>
    <%= f.submit "Save", id: "save-new-revision", name: "save_new_revision", class: "btn btn-primary", data: confirm(title: "Save New Revision", message: "This will save any changes you've made as a new revision. Are you sure?") %>
    <%= f.submit "Update", name: "update", class: "btn btn-primary", data: confirm(title: "Update Revision", message: "This will only update the survey title and revision title (discarding all other changes). Are you sure?") %>

    <% unless @revision.active? %>
      <%= f.submit "Activate", name: "activate", class: "btn btn-primary", data: confirm(title: "Activate Revision", message: "This will discard all changes except the survey title and revision title, and activate this revision. Are you sure?") %>
    <% end %>

    <%= link_to "Cancel", surveys_path, class: "btn btn-default" %>
    <%= link_to "Demo", demo_survey_path(@survey, revision_id: @revision.id), class: "btn btn-default" %>
  <% end %>

  <% if @revision.deletable? %>
    <br />
    <%= button_to "Delete", survey_path(@survey, revision_id: @revision.id), method: :delete, class: "btn btn-danger", data: confirm(title: "Delete Revision") %>
  <% end %>
<% end %>

app/views/surveys/submit_demo.html.erb
<% content_for :title, "Demo Survey" %>

<% content_for :content_size, "col-sm-9 col-md-10" %>

<% content_for :content do %>
  <h3><%= @survey.title %> <small><em><%= @revision.title %></em></small></h3>
  <%= render partial: "surveys/survey_answers", locals: { survey: @survey, revision: @revision, answers: @answers } %>
  <%= link_to "Demo Again", demo_survey_path(@survey, revision_id: @revision.id), class: "btn btn-default" %>
  <%= link_to "Done", survey_path(@survey, revision_id: @revision.id), class: "btn btn-default" %>
<% end %>