config/routes.rb
Rails.application.routes.draw do
  if !Rails.env.production? && Rails.application.config.action_mailer.delivery_method == :letter_opener_web
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users
  resources :bins, only: %i[index new create edit update destroy]
  resources :bin_locations, only: %i[index destroy]
  resources :categories, only: %i[new create edit update destroy]

  resources :counties, only: %i[new create edit update index] do
    collection do
      get :assigned
      get :unassigned
    end
  end

  resources :donations, only: %i[index new create show edit update destroy] do
    collection do
      get :closed
      get :deleted
      get :migrate
      post :migrate, action: :save_migration
    end

    member do
      post :close
      patch :restore
      post :sync
      delete :destroy_closed
    end
  end

  resources :donors, only: %i[index new edit update create destroy] do
    collection do
      get :deleted
      get :export
      post :netsuite_import
    end

    member do
      patch :restore
    end
  end

  resources :help_links, only: %i[index create destroy] do
    member do
      post :toggle_visibility
      post :move_up
      post :move_down
    end
  end

  resources :items, path: "/inventory" do
    collection do
      get :deleted
      get :bulk_pricing
      post :update_bulk_pricing
    end

    member do
      patch :restore
      get :edit_stock
    end
  end

  resources :item_program_ratios, only: %i[index new create edit update destroy]

  resources :inventory_reconciliations, only: %i[index create show destroy] do
    resources :count_sheets, only: %i[index show update destroy] do
      collection do
        delete :unnecessary, action: :destroy_unnecessary
      end
    end

    collection do
      get :print_prep
      get :completed
    end

    member do
      get :deltas
      get :ignored_bins
      post :unignore_bin
      post :comment
      post :complete
    end
  end

  resources :net_suite_errors, only: %i[index show destroy]
  resources :notifications, only: %i[index show update]

  resources :orders, only: %i[index new create edit update] do
    collection do
      get :rejected, :closed, :canceled
    end

    member do
      post :sync
      post :resync_journal_line_items
      get :survey_answers
    end
  end

  resources :organizations do
    collection do
      get :by_program
      get :deleted
      post :netsuite_import
    end

    member do
      patch :restore
    end
  end

  resources :programs, only: %i[index new create show update]

  resources :purchases, only: %i[index new create edit show update] do
    collection do
      get :closed, :canceled
    end

    member do
      post :sync
      patch :cancel
    end
  end

  resources :purchase_details, only: %i[create destroy]
  resources :purchase_shipments, only: %i[create destroy]
  resources :purchase_shorts, only: %i[create destroy]

  resources :reports, only: [] do
    collection do
      get :donor_receipts
      get :graphs
      get :inventory_adjustments
      get :net_suite_export
      get :total_inventory_value
      get :value_by_county
      get :value_by_donor
      get :price_point_variance
    end
  end

  resources :revenue_streams, only: %i[index new create show update destroy] do
    collection do
      get :deleted
    end

    member do
      patch :restore
    end
  end

  resources :surveys, only: %i[index new create show update destroy] do
    member do
      get :demo
      post :demo, action: :submit_demo
    end
  end

  resources :survey_requests, only: %i[index new create show] do
    resources :answers, only: %i[show update], controller: "survey_request_answers", param: :org_request_id do
      member do
        get :view
        post :skip
      end
    end

    member do
      get :email
      get :export
      get :report
      post :email, action: :submit_email
    end
  end

  resources :tracking_details

  resources :user_invitations, path: "/users/invitations", only: %i[new create show update] do
    collection do
      get :open
      get :closed
    end
  end

  resources :users, only: %i[index edit update destroy] do
    collection do
      get :deleted
      get :export
    end

    member do
      post :reset_password
    end
  end

  resources :vendors, only: %i[index new edit update create destroy] do
    collection do
      get :deleted
      post :netsuite_import
    end

    member do
      patch :restore
    end
  end

  resource :backup, only: :show
  resource :exports, only: :show
  resource :integrations, only: :show

  resource :profiler, only: [] do
    post :toggle
  end

  get "/.well-known/acme-challenge/:id" => "letsencrypt#authenticate"

  root to: "orders#index"
end

app/models/reports/annual_inventory_ppv.rb
module Reports
  module AnnualInventoryPpv
    def self.new()
      Reports::AnnualInventoryPpv::AllYears.new()
    end

    def self.years
      AnnualInventoryPpv.all.pluck(:year).uniq.sort
    end

    module Base
      def each
        data.each { |x| yield(*x) }
      end
    end

    class AllYears
      include Reports::AnnualInventoryPpv::Base
      attr_reader :annual_inventory_ppvs

      def initialize()
        @annual_inventory_ppvs = ::AnnualInventoryPpv.order(:year).to_a
      end

      def description_label
        "Vendor"
      end

      def data
        @data ||= annual_inventory_ppvs.map do |annual_inventory_ppv|
          [annual_inventory_ppv.year, annual_inventory_ppv.total_inventory_value,
           annual_inventory_ppv.annual_ppv,annual_inventory_ppv.real_inventory_value]
        end
      end
    end
  end
end

app/models/reports/donor_export.rb
module Reports
  class DonorExport
    include CsvExport

    FIELDS = %w[id name email cell_phone other_phone address date_created external_id external_type].freeze

    def initialize(current_user, _session)
      @current_user = current_user
      @donors = Donor.includes(:addresses).active.order(:name)
    end

    def each
      @donors.each do |donor|
        yield Row.new(donor)
      end
    end

    class Row
      attr_reader :donor, :cell_phone, :other_phone, :address, :date_created, :external_id

      delegate :id, :name, :email, :external_type, to: :donor

      def initialize(donor)
        @donor = donor
        @cell_phone = donor.primary_number
        @other_phone = donor.secondary_number
        @address = donor.primary_address
        @date_created = donor.created_at.strftime("%m/%d/%Y")
        @external_id = NetSuiteIntegration.external_id_or_status_text(donor)
      end
    end
  end
end

app/models/reports/donor_receipts.rb
module Reports
  class DonorReceipts
    def initialize(params, session)
      @params = params
      @filter = Reports::Filter.new(session)
    end

    def donors
      donor_ids = @filter.apply_date_filter(Donation.closed, :donation_date).distinct.pluck(:donor_id)
      Donor.where(id: donor_ids).order(:name).to_a
    end

    def receipts
      donations_by_donor = @filter.apply_date_filter(Donation.closed, :donation_date)
                                  .where(donor_id: @params[:donor_ids])
                                  .includes([{ donor: :addresses }, { donation_details: :item }])
                                  .to_a.group_by(&:donor)

      result = donations_by_donor.map do |donor, donations|
        Reports::DonorReceipts::Receipt.new(donor, donations)
      end

      result.sort_by { |receipt| receipt.donor.name }
    end

    class Receipt
      attr_reader :donor, :donations

      def initialize(donor, donations)
        @donor = donor
        @donations = donations
      end

      def date
        Time.zone.now
      end

      def donor_full_name
        donor.name
      end

      def donor_first_name
        if donor.external_type == "Individual"
          donor.name.split(/\s+/).first
        else
          donor.name
        end
      end

      def donor_address
        donor.first_address
      end

      def donor_address_line_1
        if donor_address.all_parts_present?
          donor_address.street_address
        else
          donor_address
        end
      end

      def donor_address_line_2
        "#{donor_address.city}, #{donor_address.state} #{donor_address.zip}" if donor_address.all_parts_present?
      end

      def donor_email
        donor.email
      end

      def total_items
        donation_items.map(&:quantity).sum
      end

      def donation_items
        @donation_items ||=
          begin
            item_map = {}

            @donations.each do |d|
              d.donation_details.each do |detail|
                item_map[detail.item_id] ||= DonorReceipts::Item.new(detail.item.description)
                item_map[detail.item_id].add(detail.quantity)
              end
            end

            item_map.values.sort_by(&:description)
          end
      end
    end

    class Item
      attr_reader :description, :quantity

      def initialize(description, quantity = 0)
        @description = description
        @quantity = quantity
      end

      def add(amount)
        @quantity += amount
      end
    end
  end
end

app/models/reports/filter.rb
module Reports
  class Filter
    def initialize(session)
      @session = session
    end

    def apply_date_filter(scope, column)
      if filtering_by_date?
        from = Date.strptime(start_date, "%m/%d/%Y").beginning_of_day
        to = Date.strptime(end_date, "%m/%d/%Y").end_of_day
        scope.where(column => (from..to))
      else
        scope
      end
    end

    def filtering_by_date?
      start_date.present? && end_date.present?
    end

    def start_date
      @session[:report_start_date]
    end

    def end_date
      @session[:report_end_date]
    end
  end
end

app/models/reports/graphs.rb
module Reports
  class Graphs
    def order_count_by_day
      total = 0

      order_count = Order.group("date(created_at)").count
      order_count = order_count.sort_by { |k, _| k }.to_h
      order_count.to_h do |k, v|
        total += v
        [k, total]
      end
    end

    def order_count_by_month
      results = {}

      order_count = Order.all.group_by { |m| m.created_at.beginning_of_month }
      order_count.each { |k, v| results[k.to_date] = v.count }

      results
    end

    def items_sent_count_by_month
      results = {}

      order_details = OrderDetail.joins(:order).where(orders: { status: 6 })
                                 .group_by { |m| m.created_at.beginning_of_month }
      order_details.each { |datetime, od| results[datetime.strftime("%b %y")] = od.map(&:quantity).sum }

      results
    end
  end
end

app/models/reports/inventory_flux.rb
module Reports
  class InventoryFlux
    attr_reader :params

    def initialize(params, session)
      @params = params
      @session = session
      @filter = Reports::Filter.new(session)
    end

    def categories
      @categories ||=
        if params[:category_id].present?
          [Category.find(params[:category_id])]
        else
          Category.all
        end
    end

    def too_broad?
      params[:category_id].blank? &&
        params[:item_id].blank? &&
        params[:report_start_date].blank? &&
        params[:report_end_date].blank?
    end

    def each
    end
  end
end

app/models/reports/net_suite/base_export.rb
module Reports
  module NetSuite
    class BaseExport
      attr_reader :user, :report_type, :session

      def initialize(user, report_type, session)
        @user = user
        @report_type = report_type
        @session = session
      end

      def build
        case report_type
        when "donations" then build_donations_exporter
        when "donors" then build_donors_exporter
        when "orders" then build_orders_exporter
        when "organizatios" then build_organizatios_exporter
        end
      end

      def build_donations_exporter
        Reports::NetSuite::DonationExport.new(session) if user.can_view_donations?
      end

      def build_donors_exporter
        Reports::NetSuite::DonorExport.new(session) if user.can_view_donations?
      end

      def build_orders_exporter
        Reports::NetSuite::OrderExport.new(session)
      end

      def build_organizatios_exporter
        Reports::NetSuite::OrganizationExport.new(session) if user.can_create_organization?
      end
    end
  end
end

app/models/reports/net_suite/donation_export.rb
module Reports
  module NetSuite
    class DonationExport
      include CsvExport

      FIELDS = %w[donationId donationDate donorName donorEmail addr_1 addr_2 city state zip
                  donorExternalId donorExternalType memo itemName value revenueStream].freeze

      def initialize(session)
        @session = session
        filter = Reports::Filter.new(@session)
        records = Donation.active_with_includes.order(:id)
        @donations = filter.apply_date_filter(records, :donation_date)
      end

      def records_present?
        @donations.exists?
      end

      def each
        @donations.each do |donation|
          yield Row.new(donation)
        end
      end

      class Row
        attr_reader :donation, :donor, :addr_1, :addr_2, :city, :state, :zip

        delegate :name, :email, :external_id, :external_type, to: :donor, prefix: true
        delegate :id, to: :donation, prefix: true

        def initialize(donation)
          @donation = donation
          @donor = donation.donor
          extract_address
        end

        def donation_date
          donation.donation_date.strftime("%m/%d/%Y")
        end

        def memo
          ["Donation received by #{donation.user.name}", donation.notes.presence].compact.join("\n")
        end

        def item_name
          "in-kind donation"
        end

        def value
          donation.value.to_s
        end

        def revenue_stream
          # Impliment with revenue streams
          nil
        end

        private

        def extract_address
          result = AddressParser.new.parse(donation.donor.primary_address)
          @attention = result[:attention]
          @addr_1 = result[:address1]
          @addr_2 = result[:address2]
          @city = result[:city]
          @state = result[:state]
          @zip = result[:zip]
        end
      end
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  active_tab "reports"

  require_permission :can_view_reports?
  before_action :store_filters

  def donor_receipts
    if params[:donor_ids].present?
      @receipts = Reports::DonorReceipts.new(params, session).receipts
      render layout: "blank_print"
    elsif params[:report_start_date].present? && params[:report_end_date].present?
      @donors = Reports::DonorReceipts.new(params, session).donors
    end
  end

  def graphs
    @graphs = Reports::Graphs.new
  end

  def inventory_adjustments
    params[:start_date] ||= 1.month.ago.strftime("%m/%d/%Y")
    params[:end_date] ||= Time.zone.now.strftime("%m/%d/%Y")
    @report = Reports::InventoryAdjustments.new(params, session)

    if params[:csv].present?
      send_csv @report, filename: @report.csv_filename
    end
  end

  def net_suite_export
    if report_exporter&.records_present?
      send_csv report_exporter, filename: "net-suite-#{net_suite_params[:report_type]}-#{Time.zone.today}.csv"
    else
      redirect_to integrations_path(net_suite_params), flash: {
        notice: "No records present for this report with these filters"
      }
    end
  end

  def total_inventory_value
    params[:date] ||= Time.zone.now.strftime("%m/%d/%Y")
    @report = Reports::TotalInventoryValue.new(params, session)

    if params[:csv].present?
      send_csv @report, filename: @report.csv_filename
    end
  end

  def value_by_donor
    @report = Reports::ValueByDonor.new(params, session)
  end

  def value_by_county
    @report = Reports::ValueByCounty.new(params, session)
  end

  def price_point_variance
    @report = Reports::PricePointVariance.new(params, session)
  end

  private

  def report_exporter
    @report_exporter ||=
      Reports::NetSuite::BaseExport.new(current_user, net_suite_params[:report_type], session).build
  end

  def store_filters
    %i[report_start_date report_end_date].each do |key|
      session[key] = params[key] if params.include?(key)
    end
  end

  def net_suite_params
    params.permit(:report_type, :report_start_date, :report_end_date)
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
  def net_suite_export_select_options
    [
      ["NetSuite Donations Export", :donations],
      ["NetSuite Donors Export", :donors],
      ["NetSuite Orders Export", :orders],
      ["NetSuite Organizations Export", :organizations]
    ]
  end
end

app/views/reports/_items_by_month.html.erb
<div class="row">
  <h3 class="col-xs-12">
    Items by Month
  </h3>

  <div class="col-xs-12">
    <%= area_chart report_items_by_month %>
  </div>
</div>

app/views/reports/_items_sent_by_month.html.erb
<div class="row">
  <h3 class="col-xs-12">
    Items Sent by Month
  </h3>

  <div class="col-xs-12">
    <%= column_chart report_items_sent_by_month %>
  </div>
</div>

app/views/reports/_orders_by_month.html.erb
<div class="row">
  <h3 class="col-xs-12">
    Orders by Month
  </h3>

  <div class="col-xs-12">
    <%= area_chart report_by_month %>
  </div>
</div>

app/views/reports/_print_value_by_county.html.erb
<% if local_assigns[:county].present? %>
  <tr><td><h3><%= county %></h3></td></tr>
<% end %>

<tr>
  <th><%= report.description_label %></th>
  <th class="text-center">Number of Items</th>
  <th class="text-center">Value of Orders</th>
</tr>

<% report.each do |description, item_count, value| %>
  <tr>
    <td><%= description %></td>
    <td class="text-center"><%= item_count %></td>
    <td class="text-center"><%= number_to_currency value, precision: 2 %></td>
  </tr>
<% end %>

<tr>
  <th>Total</th>
  <th class="text-center"><%= report.total_item_count %></th>
  <th class="text-center"><%= number_to_currency report.total_value, precision: 2 %></th>
</tr>

app/views/reports/_report_date_filters.html.erb
<div class="form-group form-group-sm">
  <label for="report-start-date" class="control-label">Start Date</label>
  <input type="text" id="report-start-date" name="report_start_date" value="<%= session[:report_start_date] %>" class="form-control" data-provide="datepicker" autocomplete="off" />
</div>

<div class="form-group form-group-sm">
  <label for="report-end-date" class="control-label">End Date</label>
  <input type="text" id="report-end-date" name="report_end_date" value="<%= session[:report_end_date] %>" class="form-control" data-provide="datepicker" autocomplete="off" />
</div>

app/views/reports/_report_filters.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= form_tag "", method: :get, class: "form-inline pull-right" do %>
      <% if local_assigns[:additional_params] %>
        <% additional_params.each do |k, v| %>
          <%= hidden_field_tag k, v %>
        <% end %>
      <% end %>

      <%= render partial: "report_date_filters" %>
      <input type="submit" value="Filter" class="btn btn-default" />
    <% end %>
  </div>
</div>

<br />

app/views/reports/_total_inventory_value_table.html.erb
<table class="table table-striped table-responsive data-table">
  <thead>
    <tr>
      <th class="sort-asc">Category</th>
      <th>Item</th>
      <th class="text-center num-value">Count</th>
      <th class="text-center monetary-value">Value</th>
      <th class="text-center monetary-value">PPV</th>
    </tr>
  </thead>

  <tbody>
    <% report.each do |category_name, item_name, count, value, ppv| %>
      <tr>
        <td><%= category_name %></td>
        <td><%= item_name %></td>
        <td class="text-center"><%= count %></td>
        <td class="text-center"><%= number_to_currency value, precision: 2 %></td>
        <td class="text-center"><%= number_to_currency ppv, precision: 2 %></td>
      </tr>
    <% end %>
  </tbody>

  <tfoot>
    <tr>
      <th></th>
      <th></th>
      <th class="text-center"></th>
      <th class="text-center"></th>
      <th class="text-center"></th>
    </tr>
  </tfoot>
</table>

app/views/reports/_value_by_county_table.html.erb
<table class="table table-striped table-responsive data-table">
  <thead>
    <tr>
      <th class="sort-asc"><%= report.description_label %></th>
      <th class="text-center num-value">Number of Items</th>
      <th class="text-center">Value of Orders</th>
    </tr>
  </thead>

  <tbody>
    <% report.each do |description, item_count, value| %>
      <tr>
        <td><%= description %></td>
        <td class="text-center"><%= item_count %></td>
        <td class="text-center"><%= number_to_currency value, precision: 2 %></td>
      </tr>
    <% end %>
  </tbody>

  <tfoot>
    <tr>
      <th>Total</th>
      <th class="text-center"><%= report.total_item_count %></th>
      <th class="text-center"><%= number_to_currency report.total_value, precision: 2 %></th>
    </tr>
  </tfoot>
</table>

app/views/reports/annual_inventory_ppv.html.erb
<% content_for :title, "Annual Inventory PPV Report" %>

<% content_for :content_size, "col-sm-9 col-md-10" %>

<% content_for :content do %>
  <div class="tab-content">
    <div class="row">
      <div class="col-xs-12">
        <table class="table table-striped table-responsive data-table">
          <thead>
            <tr>
              <th class="sort-asc">Year</th>
              <th class="text-center">Total Inventory Value</th>
              <th class="text-center">annual PPV</th>
              <th class="text-center">Real Inventory Value</th>
            </tr>
          </thead>

          <tbody>
            <% @report.each do |year, total_inventory_value, annual_ppv, real_inventory_value| %>
              <%= content_tag "tr" do %>
                <td><%= year %></td>
                <td class="text-center"><%= number_to_currency total_inventory_value, precision: 2 %></td>
                <td class="text-center"><%= number_to_currency annual_ppv, precision: 2 %></td>
                <td class="text-center"><%= number_to_currency real_inventory_value, precision: 2 %></td>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<% end %>

app/views/reports/graphs.html.erb
<% content_for :title, "Graph Reports" %>

<% content_for :content_size, "col-sm-9" %>

<% content_for :sidebar do %>
  <ul class="nav nav-pills nav-stacked">
    <%= tab("All Graphs", graphs_reports_path, params[:graph].blank?) %>
    <%= tab("Items Sent by Month", graphs_reports_path(graph: "items_sent_by_month"), params[:graph] == "items_sent_by_month") %>
    <%= tab("Orders by Day", graphs_reports_path(graph: "by_day"), params[:graph] == "by_day") %>
    <%= tab("Orders by Month", graphs_reports_path(graph: "by_month"), params[:graph] == "by_month") %>
  </ul>
<% end %>

<% content_for :content do %>
  <div class="tab-content">
    <% case params[:graph] %>
    <% when "items_sent_by_month" %>
      <%= render partial: "reports/items_sent_by_month", locals: { report_items_sent_by_month: @graphs.items_sent_count_by_month } %>
    <% when "by_day" %>
      <%= render partial: "reports/orders_by_date", locals: { report_by_date: @graphs.order_count_by_day } %>
    <% when "by_month" %>
      <%= render partial: "reports/orders_by_month", locals: { report_by_month: @graphs.order_count_by_month } %>
    <% else %>
      <%= render partial: "reports/items_sent_by_month", locals: { report_items_sent_by_month: @graphs.items_sent_count_by_month } %>
      <hr/>
      <%= render partial: "reports/orders_by_date", locals: { report_by_date: @graphs.order_count_by_day } %>
      <hr/>
      <%= render partial: "reports/orders_by_month", locals: { report_by_month: @graphs.order_count_by_month } %>
    <% end %>
  </div>
<% end %>

app/views/reports/inventory_flux.html.erb
<% content_for :title, "Inventory Flux Report" %>

<% content_for :content do %>
  <div class="row">
    <div class="col-xs-12">
      <%= form_tag inventory_flux_reports_path, method: :get, class: "form-inline text-right" do %>
        <span class="text-left">
          <select class="select2 form-control" name="category_id" data-select2-width="20%">
            <option value="" <%= "selected" if params[:category_id].blank? %>>All Categories</option>

            <% Category.all.each do |category| %>
              <option value="<%= category.id %>" <%= "selected" if params[:category_id].present? && category.id == params[:category_id].to_i %>><%= category.description %></option>
            <% end %>
          </select>
        </span>

        <span class="text-left">
          <select class="select2 form-control" name="item_id" data-select2-width="20%">
            <option value="" <%= "selected" if params[:item_id].blank? %>>All Items</option>

            <% @report.categories.each do |category| %>
              <optgroup label="<%= category.description %>">
                <% category.items.each do |item| %>
                  <option value="<%= item.id %>" data-search-text="<%= category.description %> <%= item.description %>"><%= item.description %></option>
                <% end %>
              </optgroup>
            <% end %>
          </select>
        </span>

        <%= render partial: "report_date_filters" %>
        <input type="submit" value="Filter" class="btn btn-default" />
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <% if @report.too_broad? %>
        <br />

        <div class="alert alert-info">
          Please narrow your filters to run the report.
        </div>
      <% else %>
        <table class="table table-striped table-responsive data-table">
          <thead>
            <tr>
              <th class="sort-asc">Item</th>
              <th class="text-center no-total">Incoming Quantity</th>
              <th class="text-center no-total">Incoming Value</th>
              <th class="text-center no-total">Outgoing Quantity</th>
              <th class="text-center no-total">Outgoing Value</th>
            </tr>
          </thead>

          <tbody>
            <% @report.each do |label, incoming_quantity, incoming_value, outgoing_quantity, outgoing_value| %>
              <tr>
                <td><%= label %></td>
                <td class="text-center"><%= incoming_quantity %></td>
                <td class="text-center"><%= number_to_currency(incoming_value, precision: 2) %></td>
                <td class="text-center"><%= outgoing_quantity %></td>
                <td class="text-center"><%= number_to_currency(outgoing_value, precision: 2) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
<% end %>

app/views/reports/total_inventory_value.html.erb
<% content_for :title, "Total Inventory Value Report" %>

<% content_for :content_size, "col-sm-9 col-md-10" %>

<% content_for :sidebar do %>
  <ul class="nav nav-pills nav-stacked" role="tablist">
    <%= tab("All Categories", total_inventory_value_reports_path, params[:category_id].blank?) %>
    <% Category.all.each do |category| %>
      <%= tab(category.description, total_inventory_value_reports_path(category_id: category.id, date: params[:date]), params[:category_id].present? && category.id == params[:category_id].to_i) %>
    <% end %>
  </ul>
<% end %>

<% content_for :content do %>
  <div class="hidden-print">
    <div class="tab-content">
      <%= render partial: "total_inventory_value_filters" %>
      <%= render partial: "reports/total_inventory_value_table", locals: { report: @report } %>
    </div>
  </div>
<% end %>

app/views/reports/value_by_county.html.erb
<% content_for :title, "Value By County Report" %>

<% content_for :content_size, "col-sm-9 col-md-10" %>

<% content_for :sidebar do %>
  <div class="hidden-print">
    <ul class="nav nav-pills nav-stacked" role="tablist">
      <%= tab("All Counties", value_by_county_reports_path, params[:county].blank? && params[:all_orgs] != "true") %>
      <%= tab("All Organizations", value_by_county_reports_path(all_orgs: true), params[:all_orgs] == "true") %>
      <% Reports::ValueByCounty.counties.each do |county| %>
        <%= tab(county, value_by_county_reports_path(county: county), county == params[:county]) %>
      <% end %>
    </ul>
  </div>
<% end %>

<% content_for :content do %>
  <div class="hidden-print">
    <div class="tab-content">
      <%= render partial: "report_filters" %>

      <% if params[:all_orgs] == "true" %>
        <% @report.reports.each do |report| %>
          <h3><%= report.county %></h3>
          <%= render partial: "reports/value_by_county_table", locals: { report: report } %>
        <% end %>
      <% else %>
        <%= render partial: "reports/value_by_county_table", locals: { report: @report } %>
      <% end %>
    </div>
  </div>

  <div class="visible-print-block">
    <% if params[:all_orgs] == "true" %>
      <table class="print-table">
        <tbody>
          <% @report.reports.each do |report| %>
            <%= render partial: "reports/print_value_by_county", locals: { report: report, county: report.county} %>
          <% end %>
          </tbody>
        </table>
    <% else %>
      <table class="print-table">
        <tbody>
          <%= render partial: "reports/print_value_by_county", locals: { report: @report } %>
        </tbody>
      </table>
    <% end %>
  </div>
<% end %>

app/views/reports/value_by_donor.html.erb
<% content_for :title, "Value By Donor Report" %>

<% content_for :content_size, "col-sm-9 col-md-10" %>

<% content_for :sidebar do %>
  <ul class="nav nav-pills nav-stacked" role="tablist">
    <%= tab("All Donors", value_by_donor_reports_path, params[:donor].blank?) %>
  </ul>

  <p class="top15">
    <select class="donor-selector select-href select2-with-customized-search-text">
      <option value="">Select donor</option>
      <% Donor.order(:name).each do |donor| %>
        <option data-href="<%= value_by_donor_reports_path(donor: donor.id) %>" data-search-text="<%= donor.name %> - <%= donor.primary_address %> - <%= donor.email %>" <%= "selected" if donor.id == params[:donor].to_i %>><%= donor.name %></option>
      <% end %>
    </select>
  </p>
<% end %>

<% content_for :content do %>
  <div class="tab-content">
    <%= render partial: "report_filters" %>

    <% if params[:donor].present? %>
      <h3><%= @report.donor.name %></h3>
    <% end %>

    <div class="row">
      <div class="col-xs-12">
        <table class="table table-striped table-responsive data-table">
          <thead>
            <tr>
              <th class="sort-asc"><%= @report.description_label %></th>
              <th class="text-center num-value">Number of Items</th>
              <th class="text-center monetary-value">Value of Donation</th>
            </tr>
          </thead>

          <tbody>
            <% @report.each do |description, item_count, value, donor_id| %>
              <%= content_tag "tr", ({ data: { href: value_by_donor_reports_path(donor: donor_id) } } if donor_id) do %>
                <td><%= description %></td>
                <td class="text-center"><%= item_count %></td>
                <td class="text-center"><%= number_to_currency value, precision: 2 %></td>
              <% end %>
            <% end %>
          </tbody>

          <tfoot>
            <tr>
              <th>Total</th>
              <th class="text-center"><%= @report.total_item_count %></th>
              <th class="text-center"><%= number_to_currency @report.total_value, precision: 2 %></th>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
  </div>
<% end %>